# Semester Assignment Beginnings

**This is where I will mess around with ideas on what I can do for the semester assignment**

### Baseball

Train multiple regression models (with different variables in different configurations) on a few players' stats and try to estimate how they will perform in the future (with past data so you can check the results). Run uncertianty analyses on the regression models with some simulations to see how accurate the results are.

Explain basic baseball rules to understand what the different variables mean (will add free words to the assignment).

Visualize the data, make some initial deductions and preform some exploratory analyses to get a deeper insight of the data.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pd.set_option('display.max_columns', None)

In [ ]:
# Limiting what columns are inluded to only get the relevant information.
appearances = pd.read_csv('Data/appearances.csv', 
                          usecols = ['year', 'player_id', 'team_id', 'league_id', 
                                     'g_all', 'g_batting', 'g_defense', 'g_p', 'g_c', 
                                     'g_1b', 'g_2b', 'g_3b', 'g_ss', 'g_of'])
batting = pd.read_csv('Data/batting.csv', 
                      usecols = ['year', 'player_id', 'stint', 'league_id', 'team_id', 
                                 'ab', 'r', 'h', 'hr', 'rbi', 'bb', 'hbp', 'sf'])
fielding = pd.read_csv('Data/fielding.csv', 
                       usecols = [['year', 'player_id', 'stint', 'team_id', 'league_id', 
                                   'pos', 'g', 'inn_outs', 'po', 'a', 'e', 'dp', 'pb', 
                                   'wp', 'sb', 'cs', 'zr']])
pitching = pd.read_csv('Data/pitching.csv', 
                       usecols = ['year', 'player_id', 'stint', 'team_id', 'league_id', 
                                  'w', 'l', 'g', 'gs', 'cg', 'sho', 'sv', 'ipouts', 'h', 
                                  'er', 'hr', 'bb', 'so', 'baopp', 'era', 'ibb', 'wp', 
                                  'hbp', 'bk', 'bfp', 'gf', 'r', 'sh', 'sf', 'g_idp'])
player = pd.read_csv('Data/player.csv', 
                     usecols = ['player_id', 'birth_year', 'name_first', 'name_last', 
                                'weight', 'height'])
salary = pd.read_csv('Data/salary.csv', 
                     usecols = ['year', 'player_id', 'team_id', 'league_id', 'salary'])

In [7]:
appearances = pd.read_csv('Data/appearances.csv')
batting = pd.read_csv('Data/batting.csv')
fielding = pd.read_csv('Data/fielding.csv')
pitching = pd.read_csv('Data/pitching.csv')
player = pd.read_csv('Data/player.csv')
salary = pd.read_csv('Data/salary.csv')

In [ ]:
len(appearances['player_id'].unique())

In [8]:
fielding

,player_id,year,stint,team_id,league_id,pos,g,gs,inn_outs,po,a,e,dp,pb,wp,sb,cs,zr
0,abercda01,1871,1,TRO,NaN,SS,1,NaN,NaN,1.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,2B,22,NaN,NaN,67.0,72.0,42.0,5.0,NaN,NaN,NaN,NaN,NaN
2,addybo01,1871,1,RC1,NaN,SS,3,NaN,NaN,8.0,14.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN
3,allisar01,1871,1,CL1,NaN,2B,2,NaN,NaN,1.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,allisar01,1871,1,CL1,NaN,OF,29,NaN,NaN,51.0,3.0,7.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170521,younger03,2015,1,ATL,NL,OF,22,NaN,NaN,45.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
170522,younger03,2015,2,NYN,NL,OF,7,NaN,NaN,5.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
170523,zimmery01,2015,1,WAS,NL,OF,1,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
170524,zobribe01,2015,1,OAK,AL,OF,29,NaN,NaN,39.0,0.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN
170525,zobribe01,2015,2,KCA,AL,OF,20,NaN,NaN,36.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN

In [9]:
batting

,player_id,year,stint,team_id,league_id,g,ab,r,h,double,triple,hr,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,g_idp
0,abercda01,1871,1,TRO,NaN,1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118.0,30.0,32.0,6.0,0.0,0.0,13.0,8.0,1.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137.0,28.0,40.0,4.0,5.0,0.0,19.0,3.0,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133.0,28.0,44.0,10.0,2.0,2.0,27.0,1.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120.0,29.0,39.0,11.0,3.0,0.0,16.0,6.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101327,zitoba01,2015,1,OAK,AL,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101328,zobribe01,2015,1,OAK,AL,67,235.0,39.0,63.0,20.0,2.0,6.0,33.0,1.0,1.0,33.0,26.0,2.0,0.0,0.0,3.0,5.0
101329,zobribe01,2015,2,KCA,AL,59,232.0,37.0,66.0,16.0,1.0,7.0,23.0,2.0,3.0,29.0,30.0,1.0,1.0,0.0,2.0,3.0
101330,zuninmi01,2015,1,SEA,AL,112,350.0,28.0,61.0,11.0,0.0,11.0,28.0,0.0,1.0,21.0,132.0,0.0,5.0,8.0,2.0,6.0
101331,zychto01,2015,1,SEA,AL,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
appearances

,year,team_id,league_id,player_id,g_all,gs,g_batting,g_defense,g_p,g_c,g_1b,g_2b,g_3b,g_ss,g_lf,g_cf,g_rf,g_of,g_dh,g_ph,g_pr
0,1871,BS1,NaN,barnero01,31.0,NaN,31,31.0,0,0,0,16,0,15,0,0,0,0,NaN,NaN,NaN
1,1871,BS1,NaN,barrofr01,18.0,NaN,18,18.0,0,0,0,1,0,0,13,0,4,17,NaN,NaN,NaN
2,1871,BS1,NaN,birdsda01,29.0,NaN,29,29.0,0,7,0,0,0,0,0,0,27,27,NaN,NaN,NaN
3,1871,BS1,NaN,conefr01,19.0,NaN,19,19.0,0,0,0,0,0,0,18,0,1,18,NaN,NaN,NaN
4,1871,BS1,NaN,gouldch01,31.0,NaN,31,31.0,0,0,30,0,0,0,0,0,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100946,2015,OAK,AL,zitoba01,3.0,2.0,0,3.0,3,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
100947,2015,KCA,AL,zobribe01,59.0,58.0,59,57.0,0,0,0,35,4,0,18,0,2,20,2.0,0.0,0.0
100948,2015,OAK,AL,zobribe01,67.0,63.0,67,60.0,0,0,0,34,0,0,27,0,3,29,4.0,4.0,0.0
100949,2015,SEA,AL,zuninmi01,112.0,101.0,112,112.0,0,112,0,0,0,0,0,0,0,0,0.0,1.0,0.0
100950,2015,SEA,AL,zychto01,13.0,1.0,0,13.0,13,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0

In [11]:
player

,player_id,birth_year,birth_month,birth_day,birth_country,birth_state,birth_city,death_year,death_month,death_day,death_country,death_state,death_city,name_first,name_last,name_given,weight,height,bats,throws,debut,final_game,retro_id,bbref_id
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,NaN,NaN,NaN,David,Aardsma,David Allan,220.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,NaN,NaN,NaN,Hank,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,USA,GA,Atlanta,Tommie,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,NaN,NaN,NaN,Don,Aase,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,NaN,NaN,NaN,Andy,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18841,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,2005.0,3.0,25.0,USA,CA,Burlingame,Frank,Zupo,Frank Joseph,182.0,71.0,L,R,1957-07-01,1961-05-09,zupof101,zupofr01
18842,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,NaN,NaN,NaN,NaN,NaN,NaN,Paul,Zuvella,Paul,173.0,72.0,R,R,1982-09-04,1991-05-02,zuvep001,zuvelpa01
18843,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,2014.0,9.0,8.0,USA,AZ,Tempe,George,Zuverink,George,195.0,76.0,R,R,1951-04-21,1959-06-15,zuveg101,zuverge01
18844,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,1978.0,3.0,27.0,USA,CA,La Crescenta,Dutch,Zwilling,Edward Harrison,160.0,66.0,L,L,1910-08-14,1916-07-12,zwild101,zwilldu01
18845,zychto01,1990.0,8.0,7.0,USA,IL,Monee,NaN,NaN,NaN,NaN,NaN,NaN,Tony,Zych,Anthony Aaron,190.0,75.0,R,R,2015-09-04,2015-10-03,zycht001,zychto01

In [12]:
pitching

,player_id,year,stint,team_id,league_id,w,l,g,gs,cg,sho,sv,ipouts,h,er,hr,bb,so,baopp,era,ibb,wp,hbp,bk,bfp,gf,r,sh,sf,g_idp
0,bechtge01,1871,1,PH1,NaN,1,2,3,3,2,0,0,78.0,43,23,0,11,1,NaN,7.96,NaN,NaN,NaN,0,NaN,NaN,42,NaN,NaN,NaN
1,brainas01,1871,1,WS3,NaN,12,15,30,30,30,0,0,792.0,361,132,4,37,13,NaN,4.50,NaN,NaN,NaN,0,NaN,NaN,292,NaN,NaN,NaN
2,fergubo01,1871,1,NY2,NaN,0,0,1,0,0,0,0,3.0,8,3,0,0,0,NaN,27.00,NaN,NaN,NaN,0,NaN,NaN,9,NaN,NaN,NaN
3,fishech01,1871,1,RC1,NaN,4,16,24,24,22,1,0,639.0,295,103,3,31,15,NaN,4.35,NaN,NaN,NaN,0,NaN,NaN,257,NaN,NaN,NaN
4,fleetfr01,1871,1,NY2,NaN,0,1,1,1,1,0,0,27.0,20,10,0,3,0,NaN,10.00,NaN,NaN,NaN,0,NaN,NaN,21,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44134,youngch03,2015,1,KCA,AL,11,6,34,18,0,0,0,370.0,91,42,16,43,83,0.202,3.06,0.0,5.0,0.0,0,500.0,3.0,44,4.0,2.0,NaN
44135,zieglbr01,2015,1,ARI,NL,0,3,66,0,0,0,30,204.0,48,14,3,17,36,0.197,1.85,3.0,2.0,1.0,0,263.0,46.0,17,1.0,0.0,NaN
44136,zimmejo02,2015,1,WAS,NL,13,10,33,33,0,0,0,605.0,204,82,24,39,164,0.264,3.66,3.0,2.0,8.0,1,831.0,0.0,89,8.0,2.0,NaN
44137,zitoba01,2015,1,OAK,AL,0,0,3,2,0,0,0,21.0,12,8,4,6,2,0.387,10.29,0.0,0.0,0.0,0,37.0,1.0,8,0.0,0.0,NaN
44138,zychto01,2015,1,SEA,AL,0,0,13,1,0,0,0,55.0,17,5,1,3,24,0.239,2.45,0.0,1.0,2.0,0,76.0,4.0,6,0.0,0.0,NaN

In [13]:
salary

       year team_id league_id  player_id    salary
0      1985     ATL        NL  barkele01    870000
1      1985     ATL        NL  bedrost01    550000
2      1985     ATL        NL  benedbr01    545000
3      1985     ATL        NL   campri01    633333
4      1985     ATL        NL  ceronri01    625000
...     ...     ...       ...        ...       ...
25570  2015     WAS        NL  treinbl01    512800
25571  2015     WAS        NL  ugglada01    507500
25572  2015     WAS        NL  werthja01  21000000
25573  2015     WAS        NL  zimmejo02  16500000
25574  2015     WAS        NL  zimmery01  14000000

[25575 rows x 5 columns]