# Semester Assignment Beginnings

**This is where I will mess around with ideas on what I can do for the semester assignment**

### Baseball

Train multiple regression models (with different variables in different configurations) on a few players' stats and try to estimate how they will perform in the future (with past data so you can check the results). Run uncertianty analyses on the regression models with some simulations to see how accurate the results are.

Explain basic baseball rules to understand what the different variables mean (will add free words to the assignment).

Visualize the data, make some initial deductions and preform some exploratory analyses to get a deeper insight of the data.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pd.set_option('display.max_columns', None)

In [81]:
# Limiting what columns are inluded to only get the relevant information.
batting = pd.read_csv('Data/batting.csv', 
                      usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 'g', 'ab', 'r', 'h', 'double', 'triple', 'hr', 'rbi', 'sb', 'cs', 'bb', 'so', 'hbp', 'sh', 'sf'])
fielding = pd.read_csv('Data/fielding.csv', 
                       usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 'pos', 'g', 'po', 'a', 'e', 'dp'])
pitching = pd.read_csv('Data/pitching.csv', 
                       usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 'w', 'l', 'g', 'sho', 'sv', 'ipouts', 'h', 'er', 'hr', 'bb', 'so', 'era', 'hbp', 'bk'])
player = pd.read_csv('Data/player.csv', 
                     usecols = ['player_id', 'birth_year', 'name_first', 'name_last', 
                                'weight', 'height', 'bats', 'throws'])
salary = pd.read_csv('Data/salary.csv', 
                     usecols = ['year', 'player_id', 'team_id', 'league_id', 'salary'])
team = pd.read_csv('Data/team.csv', 
                   usecols = ['year', 'league_id', 'team_id', 'franchise_id', 'div_id', 'rank', 'g', 'w', 'l', 'div_win', 'lg_win', 'ws_win', 'r', 'ab', 'h', 'double', 'triple', 'hr', 'bb', 'so', 'sb', 'cs', 'hbp', 'sf', 'era', 'sho', 'sv', 'ipouts', 'e'])

In [82]:
fielding

,player_id,year,stint,team_id,league_id,pos,g,po,a,e,dp
0,abercda01,1871,1,TRO,NaN,SS,1,1.0,3.0,2.0,0.0
1,addybo01,1871,1,RC1,NaN,2B,22,67.0,72.0,42.0,5.0
2,addybo01,1871,1,RC1,NaN,SS,3,8.0,14.0,7.0,0.0
3,allisar01,1871,1,CL1,NaN,2B,2,1.0,4.0,0.0,0.0
4,allisar01,1871,1,CL1,NaN,OF,29,51.0,3.0,7.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
170521,younger03,2015,1,ATL,NL,OF,22,45.0,0.0,0.0,0.0
170522,younger03,2015,2,NYN,NL,OF,7,5.0,0.0,0.0,0.0
170523,zimmery01,2015,1,WAS,NL,OF,1,0.0,0.0,0.0,0.0
170524,zobribe01,2015,1,OAK,AL,OF,29,39.0,0.0,3.0,0.0
170525,zobribe01,2015,2,KCA,AL,OF,20,36.0,1.0,1.0,0.0

In [83]:
player['weight'] = (player['weight'] * 0.453592).round() # Converting pounds to kg, rounding to nearest integer.
player['height'] = (player['height'] * 2.54).round() # Converting inches to cm, rounding to nearest integer.

In [84]:
player

       player_id  birth_year name_first name_last  weight  height bats throws
0      aardsda01      1981.0      David   Aardsma   100.0   190.0    R      R
1      aaronha01      1934.0       Hank     Aaron    82.0   183.0    R      R
2      aaronto01      1939.0     Tommie     Aaron    86.0   190.0    R      R
3       aasedo01      1954.0        Don      Aase    86.0   190.0    R      R
4       abadan01      1972.0       Andy      Abad    83.0   185.0    L      L
...          ...         ...        ...       ...     ...     ...  ...    ...
18841   zupofr01      1939.0      Frank      Zupo    83.0   180.0    L      R
18842  zuvelpa01      1958.0       Paul   Zuvella    78.0   183.0    R      R
18843  zuverge01      1924.0     George  Zuverink    88.0   193.0    R      R
18844  zwilldu01      1888.0      Dutch  Zwilling    73.0   168.0    L      L
18845   zychto01      1990.0       Tony      Zych    86.0   190.0    R      R

[18846 rows x 8 columns]

In [85]:
batting

,player_id,year,stint,team_id,league_id,g,ab,r,h,double,triple,hr,rbi,sb,cs,bb,so,hbp,sh,sf
0,abercda01,1871,1,TRO,NaN,1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118.0,30.0,32.0,6.0,0.0,0.0,13.0,8.0,1.0,4.0,0.0,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137.0,28.0,40.0,4.0,5.0,0.0,19.0,3.0,1.0,2.0,5.0,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133.0,28.0,44.0,10.0,2.0,2.0,27.0,1.0,1.0,0.0,2.0,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120.0,29.0,39.0,11.0,3.0,0.0,16.0,6.0,2.0,2.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101327,zitoba01,2015,1,OAK,AL,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101328,zobribe01,2015,1,OAK,AL,67,235.0,39.0,63.0,20.0,2.0,6.0,33.0,1.0,1.0,33.0,26.0,0.0,0.0,3.0
101329,zobribe01,2015,2,KCA,AL,59,232.0,37.0,66.0,16.0,1.0,7.0,23.0,2.0,3.0,29.0,30.0,1.0,0.0,2.0
101330,zuninmi01,2015,1,SEA,AL,112,350.0,28.0,61.0,11.0,0.0,11.0,28.0,0.0,1.0,21.0,132.0,5.0,8.0,2.0
101331,zychto01,2015,1,SEA,AL,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
pitching

,player_id,year,stint,team_id,league_id,w,l,g,sho,sv,ipouts,h,er,hr,bb,so,era,hbp,bk
0,bechtge01,1871,1,PH1,NaN,1,2,3,0,0,78.0,43,23,0,11,1,7.96,NaN,0
1,brainas01,1871,1,WS3,NaN,12,15,30,0,0,792.0,361,132,4,37,13,4.50,NaN,0
2,fergubo01,1871,1,NY2,NaN,0,0,1,0,0,3.0,8,3,0,0,0,27.00,NaN,0
3,fishech01,1871,1,RC1,NaN,4,16,24,1,0,639.0,295,103,3,31,15,4.35,NaN,0
4,fleetfr01,1871,1,NY2,NaN,0,1,1,0,0,27.0,20,10,0,3,0,10.00,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44134,youngch03,2015,1,KCA,AL,11,6,34,0,0,370.0,91,42,16,43,83,3.06,0.0,0
44135,zieglbr01,2015,1,ARI,NL,0,3,66,0,30,204.0,48,14,3,17,36,1.85,1.0,0
44136,zimmejo02,2015,1,WAS,NL,13,10,33,0,0,605.0,204,82,24,39,164,3.66,8.0,1
44137,zitoba01,2015,1,OAK,AL,0,0,3,0,0,21.0,12,8,4,6,2,10.29,0.0,0
44138,zychto01,2015,1,SEA,AL,0,0,13,0,0,55.0,17,5,1,3,24,2.45,2.0,0

In [87]:
salary

       year team_id league_id  player_id    salary
0      1985     ATL        NL  barkele01    870000
1      1985     ATL        NL  bedrost01    550000
2      1985     ATL        NL  benedbr01    545000
3      1985     ATL        NL   campri01    633333
4      1985     ATL        NL  ceronri01    625000
...     ...     ...       ...        ...       ...
25570  2015     WAS        NL  treinbl01    512800
25571  2015     WAS        NL  ugglada01    507500
25572  2015     WAS        NL  werthja01  21000000
25573  2015     WAS        NL  zimmejo02  16500000
25574  2015     WAS        NL  zimmery01  14000000

[25575 rows x 5 columns]

In [88]:
team

,year,league_id,team_id,franchise_id,div_id,rank,g,w,l,div_win,lg_win,ws_win,r,ab,h,double,triple,hr,bb,so,sb,cs,hbp,sf,era,sho,sv,ipouts,e
0,1871,NaN,BS1,BNA,NaN,3,31,20,10,NaN,N,NaN,401,1372,426,70,37,3,60,19.0,73.0,NaN,NaN,NaN,3.55,1,3,828,225
1,1871,NaN,CH1,CNA,NaN,2,28,19,9,NaN,N,NaN,302,1196,323,52,21,10,60,22.0,69.0,NaN,NaN,NaN,2.76,0,1,753,218
2,1871,NaN,CL1,CFC,NaN,8,29,10,19,NaN,N,NaN,249,1186,328,35,40,7,26,25.0,18.0,NaN,NaN,NaN,4.11,0,0,762,223
3,1871,NaN,FW1,KEK,NaN,7,19,7,12,NaN,N,NaN,137,746,178,19,8,2,33,9.0,16.0,NaN,NaN,NaN,5.17,1,0,507,163
4,1871,NaN,NY2,NNA,NaN,5,33,16,17,NaN,N,NaN,302,1404,403,43,21,1,33,15.0,46.0,NaN,NaN,NaN,3.72,1,0,879,227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2800,2015,NL,LAN,LAD,W,1,162,92,70,Y,N,N,667,5385,1346,263,26,187,563,1258.0,59.0,34.0,60.0,30.0,3.44,21,47,4337,75
2801,2015,NL,SFN,SFG,W,2,162,84,78,N,N,N,696,5565,1486,288,39,136,457,1159.0,93.0,36.0,49.0,37.0,3.72,18,41,4333,78
2802,2015,NL,ARI,ARI,W,3,162,79,83,N,N,N,720,5649,1494,289,48,154,490,1312.0,132.0,44.0,33.0,57.0,4.04,12,44,4400,86
2803,2015,NL,SDN,SDP,W,4,162,74,88,N,N,N,650,5457,1324,260,36,148,426,1327.0,82.0,29.0,40.0,42.0,4.09,6,41,4321,92
2804,2015,NL,COL,COL,W,5,162,68,94,N,N,N,737,5572,1479,274,49,186,388,1283.0,97.0,43.0,33.0,34.0,5.04,4,36,4279,95