# Moneyball Lite: A "Shallow-Dive" Into the World of Sabermetrics

Abstact explaining the problem I am trying to solve and hinting at what I have discovered.

Table of contents
- Introduction
    - What is Moneyball?
    - Baseball Fundamentals
- Imports
    - Libraries and Visuals
    - The Data
    - Transforming and Merging
- Modeling Simple Relationships With Linear Regression

### Introduction

##### What is Moneyball?

If you are unfamiliar, Moneyball is a book (Moneyball: The Art of Winning an Unfair Game, 2003) and a movie (2011) about the baseball team Oakland Athletics and their general manager, former professional baseball player Billy Beane, and their adoption of advanced statistics to assemble a winning team under strict budgetary constraints. It is based on the true story of how the Oakland A's encouraged a paradigm shift in the way baseball teams evaluate and choose their players and strategies. 

The story begins after an unsatisfactory season for the A's in 2001, the team is left in disarray after the departure of several key players during the post season. This leaves Beane to find replacements for the 2002 season which can hold up to the standard they expect for performance. But rather than following the outmoded counsel from his advisers (the old way of choosing players which was loosely based on the players' actual performance, with their appearance and behavior often being the deciding factors) he turned to statistics to construct a team that could compete in the big leagues with a budget of approximately 41 million USD (compared to other teams like the NY Yankees who had over 100 million USD to spend). 

Beane based his decisions heavily on the works by George William James, a baseball writer, historian, and statistician who devised an approach to determine why teams win and lose through statistical data and analyses, which he named sabermetrics (after the Society for American Baseball Research, SABR). With this unorthodox approach, Beane managed to create a team which did not only perform exceedingly well, but also kept the cost at a fraction of their competitors'. The team had a rocky start, and in turn they received plenty of criticism, but they proved their critics wrong after winning the division title (West) in the American league, and breaking the then record of 19 consecutive wins, with 20 wins in a row. 

Though the team did not live up to Beane's hope of winning the World Series, they accomplished something much bigger, the widespread adoption of advanced statistics (sabermetrics) in the world of baseball to optimize performance and spending. For example, after the Boston Red Sox took up the approach, they managed to win the World Series in 2004 after an 84-year dry spell. 

This term project will be focused on understanding some of the basics of sabermetrics by looking at historical data for teams and players, and performing some analyses with fundamental statistical techniques, and then interpreting the results. I will attempt to model relationships between the performance of a player or team, and appropriate statistics and metrics, and by doing so, hopefully get a deeper understanding of what makes a good player/team. I do, however realize that baseball is not a common sport in Norway, so to begin with, I will explain baseball to a level so that you can understand the process and results of my analyses (in the case that you are not already familiar with the sport).

##### Baseball Fundamentals

Baseball is a ball-and-bat game, each game is played between two teams (home and visiting), one on offense (batting, running) and one on defense (pitching, fielding). The playing field (often referred to as a baseball diamond) originates on the ‘home plate’ extending outward at a 45-degree angle defining the fair and foul territories. The term ‘diamond’ comes from the shape formed by the four bases (plates), they are laid out as a square with home plate (or simply home) being the foundation, the other bases are: first, second, and third, arranged in the counterclockwise direction. The area these bases surround is called the infield with the pitcher’s mound (a raised circular area where the ball is pitched from) in the center, the outfield is everywhere else there is fair territory, the outfield is also usually bounded by a wall or fence, though over this bound is still fair territory. 

A game is played in nine ‘innings’, each inning is comprised of two half-innings (top and bottom for first and second half respectively) which denote which of the teams will be batting and which will be fielding. The visiting team always starts with batting at the top of each inning. Each half-inning is ended if three batters/runners are taken ‘out’ by the fielding team, and the teams switch roles. 

The game of baseball is a complex affair, but for this project you do not need to know all the ins and outs so I will only explain the basics, and throughout the project I will explain the more intricate aspects when they become relevant. The fielding team, and their pitcher starts by throwing the ball toward the batter on the opposing team, the batter tries to hit the ball into fair territory and when he manages that he runs to first base (or the one he can manage to run to; second, third, or all the way around the diamond; a home run). The fielding team wants to get ahold of the ball so they can take the runner ‘out’ before he reaches a base plate. Outs can come from several sources, if the batter does not manage to hit the ball after three pitches, he is out, if a fielder can get the ball to first base (or another base the batter is running to) before the batter gets there, he is out, if a fielder manages to catch the ball before it hits the ground, the batter is out, three outs and the half-inning is over. The goal of the offensive team is to get as many ‘runs’ as possible, a run occurs when a runner returns safely home after running through all bases, either as a home run or multiple runs from base to base as the next batters hit. The team with the most total runs after all nine innings are over, wins. On the occasion of a tie, a new inning is added until there is a winner.

Major League Baseball (MLB) is split into two separate leagues: The National League, and the American League, each with 15 teams participating. These are again subdivided into divisions: East, Central, and West (based on the geographical location of the team). As an example, the Oakland Athletics baseball team plays in the American league, in the West division (as their location is Oakland, California). A season in baseball usually consists of 162 games for each team, the teams who are the best in each of their respective divisions earns a division title. The teams with the best records in both leagues move on to the playoffs, here every qualified team plays through a series of additional tournaments which culminates in the World Series (poorly named as it only includes the US and Canada), which decides the very best team of the season. In this project, for simplicity, I will limit my data to teams who have played or is playing in Major League Baseball, thereby excluding other leagues like the American Association and Union Association who are also included in the datasets I will use, and other countries’ baseball leagues.

### Imports

##### Libraries and Visuals

In [86]:
# LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import scipy.stats as spt
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns

In [87]:
# VISUALS
# Figure size
plt.rcParams['figure.figsize'] = [16,10]

# Text sizes
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.rcParams['axes.labelsize']= 12
plt.rcParams['font.size'] = 14

# Colors
plt.rcParams['legend.labelcolor'] = '#ffffff'
plt.rcParams['xtick.labelcolor'] = '#ffffff'
plt.rcParams['ytick.labelcolor'] = '#ffffff'
plt.rcParams['axes.labelcolor'] = '#ffffff'
plt.rcParams['axes.titlecolor'] = '#ffffff'
plt.rcParams['axes.edgecolor'] = '#ffffff'
plt.rcParams['xtick.color'] = '#ffffff'
plt.rcParams['ytick.color'] = '#ffffff'
plt.rcParams['figure.facecolor'] = '#1f1f1f'
plt.rcParams['axes.facecolor'] = '#1f1f1f'

# Graph colors
from cycler import cycler

diverse = ['#1f78b4', '#33a02c', '#e31a1c', '#ff7f00', '#6a3d9a', '#b15928', '#a6cee3', '#b2df8a', '#fb9a99']
greens = ['#2ca02c', '#4daf4a', '#45a05a', '#60bd68', '#5cb85c', '#6ba981', '#75bb6f', '#6dae64', '#4c9a5f']
blues = ['#1f78b4', '#377eb8', '#3182bd', '#4292c6', '#5aaed6', '#6baed6', '#7ba3df', '#92b3e4', '#a6bddb']
reds = ['#e41a1c', '#d73027', '#a50026', '#f46d43', '#d73027', '#fdae61', '#fee08b', '#fee08b', '#d73027']

plt.rcParams['axes.prop_cycle'] = cycler(color = diverse)

# Display max columns, pandas dataframes
pd.set_option('display.max_columns', None)

##### The Data

The data has been taken from the Lahman Baseball Database (assembled by Sean Lahman), which is a collection of historical baseball datasets dating back to 1871. The database has figures on several aspects of baseball, it has everything from information on how each individual player performed every year they played (whether they were batting, pitching, or fielding), to what the results of each season was and how each team performed that season. It also includes a lot of information I am not going to take advantage of for this project like college baseball, and what managers managed what teams in what season. I found a cleaned version (more consistent column names, less NaN values, etc.) of the database on Kaggle [1] which had data up to 2015, and I imported the most relevant datasets from the database.

I have also included a dataset including historical CPI (Consumer Price Index) data in the US so I can adjust player's salaries for inflation. I found this dataset on Kaggle as well [2].

The datasets I am importing are:
- batting.csv: Has figures on each players batting performance for every year they played.
- fielding.csv: Has figures on each players fielding performance for every year they played.
- pitching.csv: Has figures on each players pitching performance for every year they played.
- player.csv: Has information on each player's birth year, weight, height, and what their dominant hand is.
- salary.csv: Has each player's salary from each season and team they played for, not adjusted for inflation.
- team.csv: Has figures on how each team performed every year they played.
- cpi.csv: Has historical CPI values for the US.

In [88]:
# Limiting what columns are inluded to only get the relevant information.
batting = pd.read_csv('Data/batting.csv', 
                      usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 
                                 'g', 'ab', 'r', 'h', 'double', 'triple', 'hr', 'rbi', 
                                 'sb', 'cs', 'bb', 'so', 'hbp', 'sh', 'sf'])
fielding = pd.read_csv('Data/fielding.csv', 
                       usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 
                                  'pos', 'g', 'po', 'a', 'e', 'dp'])
pitching = pd.read_csv('Data/pitching.csv', 
                       usecols = ['player_id', 'year', 'stint', 'team_id', 'league_id', 
                                  'w', 'l', 'g', 'sho', 'sv', 'ipouts', 'h', 'er', 'hr', 
                                  'bb', 'so', 'era', 'hbp', 'bk', 'bfp'])
player = pd.read_csv('Data/player.csv', 
                     usecols = ['player_id', 'birth_year', 'name_first', 'name_last', 
                                'weight', 'height', 'bats', 'throws'])
salary = pd.read_csv('Data/salary.csv', 
                     usecols = ['year', 'player_id', 'team_id', 'league_id', 'salary'])
team = pd.read_csv('Data/team.csv', 
                   usecols = ['year', 'league_id', 'team_id', 'franchise_id', 'div_id', 
                              'rank', 'g', 'w', 'l', 'div_win', 'wc_win', 'lg_win', 
                              'ws_win', 'r', 'ab', 'h', 'double', 'triple', 'hr', 'bb', 
                              'so', 'sb', 'cs', 'hbp', 'sf', 'era', 'sho', 'sv', 
                              'ipouts', 'e'])
cpi = pd.read_csv('Data/cpi.csv')

As you can see, I have limited the data by choosing what columns I want to be included in the datasets, to see what features I have omitted please refer to documentation of the database: <a href = 'https://cran.r-project.org/web/packages/Lahman/Lahman.pdf'>here</a>. Some further limitations I will implement include: Only using data from the Major League (American and National League), as mentioned in the introduction. For that reason, I will also only be using data from 1876 to 2015 because neither the National or American League existed before then.

In [89]:
# Limiting data to 1876-2015 and to leagues NL and AL:
batting = batting[(batting['year'] >= 1876) & (batting['league_id'].isin(['NL', 'AL']))]
fielding = fielding[(fielding['year'] >= 1876) & (fielding['league_id'].isin(['NL', 'AL']))]
pitching = pitching[(pitching['year'] >= 1876) & (pitching['league_id'].isin(['NL', 'AL']))]
team = team[(team['year'] >= 1876) & (team['league_id'].isin(['NL', 'AL']))]

##### Transforming and Merging

In [90]:
# Converting lbs to kg and inches to m, rounding to nearest integer.
player['weight'] = (player['weight'] * 0.453592).round()
player['height'] = (player['height'] * 2.54).round() / 100

Based on this I will calculate the BMI (Body Mass Index) for each player as I will use this as a feature in regression models. Although BMI is generally not a good measure for whether someone is overweight, it might be a good predictor for a baseball players performance. I am doing this with the assumption that the players had the same weight and height all throughout their careers. BMI is calculated by: 

$BMI = \frac{weight}{height^2}$, where weight is in kilograms and height is in meters.

In [91]:
player['bmi'] = (player['weight'] / (player['height'] ** 2)).round(1)

To adjust salaries for inflation using CPI I use this formula:

$Adjusted\ Salary = \frac{Nominal\ Salary}{CPI\ For\ Ending\ Year} \cdot CPI\ For\ Base\ Year$

I do this so I can analyze and compare the salaries for players over the years. An important note is that the data only has salary information from 1985 to 2015, so the data is limited.

In [92]:
# Calculate the yearly CPI:
cpi['cpi'] = cpi[['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']].mean(axis = 1)

# Limit the CPI information to the appropriate years:
cpi = cpi[(cpi['Year'] >= 1985) & (cpi['Year'] <= 2015)]

# The year column in the CPI dataset was a float, correcting:
cpi['Year'] = cpi['Year'].astype(int)

# Renaming the column name for easier merging:
cpi = cpi.rename({'Year': 'year'}, axis = 1)

# Merging the CPI information with the salary dataset:
salary = pd.merge(salary, cpi[['year', 'cpi']], on = 'year', how = 'inner')

# Calculating the inflation adjusted salary based on the formula above:
salary['adj_salary'] = (salary['salary'] / salary['cpi']) * salary.loc[salary['year'] == 2015, 'cpi'].values[0]
salary.head()

   year team_id league_id  player_id  salary         cpi    adj_salary
0  1985     ATL        NL  barkele01  870000  107.566667  1.916995e+06
1  1985     ATL        NL  bedrost01  550000  107.566667  1.211894e+06
2  1985     ATL        NL  benedbr01  545000  107.566667  1.200876e+06
3  1985     ATL        NL   campri01  633333  107.566667  1.395513e+06
4  1985     ATL        NL  ceronri01  625000  107.566667  1.377152e+06

By checking with an inflation calculator, I can confirm that the adjusted salary is correct with some small error, I will ignore the error and say that this adjusted salary can be used to compare over time.

I will now merge the appropriate information from the salary (adjusted salary) and player (birth year, weight, height, bmi, bats, and throws) datasets into the batting, fielding, and pitching datasets. Using the **merge** function from pandas I can easily combine the data based on the necessary features. For the salary I will use year, player_id, and team_id to correctly assign the salary to the corresponding player in the right year when they played for the team that paid that salary. For the information from the player dataset I will simply use player_id to correctly assign the data to the corresponding player.

In [93]:
# Adding the pertinent information to the batting dataset:
batting = pd.merge(batting, 
                   salary[['year', 'player_id', 'team_id', 'adj_salary']], 
                   on=['year', 'player_id', 'team_id'], how='left')
batting = pd.merge(batting, 
                   player[['player_id', 'weight', 'height', 'bmi', 'bats', 
                           'throws', 'birth_year']], on=['player_id'], how='left')

# Adding the pertinent information to the fielding dataset:
fielding = pd.merge(fielding, 
                    salary[['year', 'player_id', 'team_id', 'adj_salary']], 
                    on=['year', 'player_id', 'team_id'], how='left')
fielding = pd.merge(fielding, 
                    player[['player_id', 'weight', 'height', 'bmi', 'bats', 
                            'throws', 'birth_year']], on=['player_id'], how='left')

# Adding the pertinent information to the pitching dataset:
pitching = pd.merge(pitching, 
                    salary[['year', 'player_id', 'team_id', 'adj_salary']], 
                    on=['year', 'player_id', 'team_id'], how='left')
pitching = pd.merge(pitching, 
                    player[['player_id', 'weight', 'height', 'bmi', 'bats', 
                            'throws', 'birth_year']], on=['player_id'], how='left')

Now that I have the information about birth year in every dataset, I can calculate the age of each player for every year they played. I am not considering the time of year each player was born, so the age for some of the players might not be completely accurate, but the effect will be the same as they are consistently incorrect.

In [94]:
batting['age'] = batting['year'] - batting['birth_year']
fielding['age'] = fielding['year'] - fielding['birth_year']
pitching['age'] = pitching['year'] - pitching['birth_year']

In [95]:
batting

,player_id,year,stint,team_id,league_id,g,ab,r,h,double,triple,hr,rbi,sb,cs,bb,so,hbp,sh,sf,adj_salary,weight,height,bmi,bats,throws,birth_year,age
0,addybo01,1876,1,CHN,NL,32,142.0,36.0,40.0,4.0,1.0,0.0,16.0,NaN,NaN,5.0,0.0,NaN,NaN,NaN,NaN,73.0,1.73,24.4,L,L,1842.0,34.0
1,allisar01,1876,1,LS1,NL,31,130.0,9.0,27.0,2.0,1.0,0.0,10.0,NaN,NaN,2.0,6.0,NaN,NaN,NaN,NaN,68.0,1.73,22.7,NaN,NaN,1849.0,27.0
2,allisdo01,1876,1,HAR,NL,44,163.0,19.0,43.0,4.0,0.0,0.0,15.0,NaN,NaN,3.0,9.0,NaN,NaN,NaN,NaN,73.0,1.78,23.0,R,R,1846.0,30.0
3,andrufr01,1876,1,CHN,NL,8,36.0,6.0,11.0,3.0,0.0,0.0,2.0,NaN,NaN,0.0,5.0,NaN,NaN,NaN,NaN,84.0,1.88,23.8,R,R,1850.0,26.0
4,ansonca01,1876,1,CHN,NL,66,309.0,63.0,110.0,9.0,7.0,2.0,59.0,NaN,NaN,12.0,8.0,NaN,NaN,NaN,NaN,103.0,1.83,30.8,R,R,1852.0,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97751,zitoba01,2015,1,OAK,AL,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,93.0,1.88,26.3,L,L,1978.0,37.0
97752,zobribe01,2015,1,OAK,AL,67,235.0,39.0,63.0,20.0,2.0,6.0,33.0,1.0,1.0,33.0,26.0,0.0,0.0,3.0,7500000.0,95.0,1.90,26.3,B,R,1981.0,34.0
97753,zobribe01,2015,2,KCA,AL,59,232.0,37.0,66.0,16.0,1.0,7.0,23.0,2.0,3.0,29.0,30.0,1.0,0.0,2.0,NaN,95.0,1.90,26.3,B,R,1981.0,34.0
97754,zuninmi01,2015,1,SEA,AL,112,350.0,28.0,61.0,11.0,0.0,11.0,28.0,0.0,1.0,21.0,132.0,5.0,8.0,2.0,523500.0,100.0,1.88,28.3,R,R,1991.0,24.0
97755,zychto01,2015,1,SEA,AL,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,86.0,1.90,23.8,R,R,1990.0,25.0

In [96]:
fielding

,player_id,year,stint,team_id,league_id,pos,g,po,a,e,dp,adj_salary,weight,height,bmi,bats,throws,birth_year,age
0,addybo01,1876,1,CHN,NL,OF,32,46.0,6.0,13.0,0.0,NaN,73.0,1.73,24.4,L,L,1842.0,34.0
1,allisar01,1876,1,LS1,NL,1B,8,90.0,1.0,4.0,2.0,NaN,68.0,1.73,22.7,NaN,NaN,1849.0,27.0
2,allisar01,1876,1,LS1,NL,OF,23,34.0,11.0,12.0,1.0,NaN,68.0,1.73,22.7,NaN,NaN,1849.0,27.0
3,allisdo01,1876,1,HAR,NL,C,40,201.0,43.0,33.0,2.0,NaN,73.0,1.78,23.0,R,R,1846.0,30.0
4,allisdo01,1876,1,HAR,NL,OF,6,5.0,0.0,1.0,0.0,NaN,73.0,1.78,23.0,R,R,1846.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163711,younger03,2015,1,ATL,NL,OF,22,45.0,0.0,0.0,0.0,1000000.0,88.0,1.78,27.8,B,R,1985.0,30.0
163712,younger03,2015,2,NYN,NL,OF,7,5.0,0.0,0.0,0.0,NaN,88.0,1.78,27.8,B,R,1985.0,30.0
163713,zimmery01,2015,1,WAS,NL,OF,1,0.0,0.0,0.0,0.0,14000000.0,100.0,1.90,27.7,R,R,1984.0,31.0
163714,zobribe01,2015,1,OAK,AL,OF,29,39.0,0.0,3.0,0.0,7500000.0,95.0,1.90,26.3,B,R,1981.0,34.0
163715,zobribe01,2015,2,KCA,AL,OF,20,36.0,1.0,1.0,0.0,NaN,95.0,1.90,26.3,B,R,1981.0,34.0

In [97]:
pitching

,player_id,year,stint,team_id,league_id,w,l,g,sho,sv,ipouts,h,er,hr,bb,so,era,hbp,bk,bfp,adj_salary,weight,height,bmi,bats,throws,birth_year,age
0,barnero01,1876,1,CHN,NL,0,0,1,0,0,4.0,7,3,0,0,0,20.25,NaN,0,13.0,NaN,66.0,1.73,22.1,R,R,1850.0,26.0
1,blongjo01,1876,1,SL3,NL,0,0,1,0,0,12.0,2,0,0,1,0,0.00,NaN,0,14.0,NaN,NaN,NaN,NaN,R,R,1853.0,23.0
2,bondto01,1876,1,HAR,NL,31,13,45,6,0,1224.0,355,76,2,13,88,1.68,NaN,0,1623.0,NaN,73.0,1.70,25.3,R,R,1856.0,20.0
3,bootham01,1876,1,CN1,NL,0,1,3,0,0,29.0,22,10,0,0,0,9.31,NaN,0,51.0,NaN,72.0,1.75,23.5,R,R,1848.0,28.0
4,boothed01,1876,1,NY3,NL,0,0,1,0,0,15.0,16,6,0,0,0,10.80,NaN,0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43020,youngch03,2015,1,KCA,AL,11,6,34,0,0,370.0,91,42,16,43,83,3.06,0.0,0,500.0,675000.0,116.0,2.08,26.8,R,R,1979.0,36.0
43021,zieglbr01,2015,1,ARI,NL,0,3,66,0,30,204.0,48,14,3,17,36,1.85,1.0,0,263.0,5000000.0,100.0,1.93,26.8,R,R,1979.0,36.0
43022,zimmejo02,2015,1,WAS,NL,13,10,33,0,0,605.0,204,82,24,39,164,3.66,8.0,1,831.0,16500000.0,102.0,1.88,28.9,R,R,1986.0,29.0
43023,zitoba01,2015,1,OAK,AL,0,0,3,0,0,21.0,12,8,4,6,2,10.29,0.0,0,37.0,NaN,93.0,1.88,26.3,L,L,1978.0,37.0
43024,zychto01,2015,1,SEA,AL,0,0,13,0,0,55.0,17,5,1,3,24,2.45,2.0,0,76.0,NaN,86.0,1.90,23.8,R,R,1990.0,25.0

All information has been correctly added to the datasets. Because there is no salary information until 1985, there will of course be a lot of missing values for salary, but when assessing players based on their salary I will exclude the missing values and the corresponding players to get consistent results. Because of missing values in the player information, there are some players that are not assigned the necessary information, but this will be handled when appropriate.

### Modeling Simple Relationships With Linear Regression

Baseball metrics needed to analyse player and team performance.

Some exploratory analysis of the data. Get a deeper understanding of how the data is connected. Visualize relevant data.

Creating models. Creating a few multiple linear regression models with different independent variables and explainations of why I have chosen those variables. Discuss the coefficients of the models, what do they mean, are there some which are more prevalent? Insignificant? Score the models with AIC and BIC, look at the r-squared.

Simulate the uncertainty. Explain inferential and predictive uncertainty, model it, visualize it, what conclusions can I pull from this?

Maybe do logistic regression if it is relevant, same with bayes. If relevant, model and explain. More likely time series modeling with arima forecasting.

Final discussions and conclusions.

### Sources

- Inflation adjustment formula: https://study.com/academy/lesson/adjusting-wages-for-the-inflation-rate.html#:~:text=There%20are%20two%20main%20formulas,CPI%20in%20the%20selected%20year
- Advanced stats: https://www.mlb.com/glossary/advanced-stats
- Standard stats: https://www.mlb.com/glossary/standard-stats
- Baseball database: https://www.kaggle.com/datasets/seanlahman/the-history-of-baseball
- Database docum: https://cran.r-project.org/web/packages/Lahman/Lahman.pdf
- CPI data: https://www.kaggle.com/datasets/neelgajare/usa-cpi-inflation-from-19132022
- BMI formula: https://www.calculatorsoup.com/calculators/health/bmi-calculator.php

### Needs to be in the project:

<input type = 'checkbox'> Data management and transformation (working with the data, building the datasets).<br>
<input type = 'checkbox'> Exploratiory and descriptive analysis (Visualizing, tables, test statistics).<br>
<input type = 'checkbox'> A simple regression and appropriate visualization of uncertainty.<br>
<input type = 'checkbox'> Multiple regression and associated diagnostics and visualization. Don't use time series data for this or the previous point.<br>
<input type = 'checkbox'> 'Fake' data simulation to explore model validity. (Test one or more of the assumptions of a regression analysis).<br>
<input type = 'checkbox'> Diagnostics and model evaluation (residuals vs. fitted, AIC/BIC, inferential and predictive uncertainty).<br>
<input type = 'checkbox'> Discussion of identification an causality.<br>
<input type = 'checkbox'> At least one of logistic regression (GLM models), Bayesian/decision analysis, or time series analysis.

Logistic regression to try to predict whether a team wins the division title based on the team average of multiple different metrics.

Simple linear regression to model runs based on a players age.

Multiple linear regression to try to estimate a players (OBP, BA, SLG, OPS) based on their age, weight, height, what arm they bat and throw with.

Multiple linear regression to try to estimate a players monetary worth (as salary) based on their performance.